In [1]:
! pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.16.2)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 6.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.1 MB 7.9 MB/s eta 0:00:01
   ------------------ --------------------- 3.7/8.1 MB 8.4 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.1 MB 5.6 MB/s eta 0:00:01
   ---------------------- ----------------- 4.5/8.1 MB 5.1 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 4.5 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 4.2 MB/s  0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
! pip install --upgrade pip

Requirement already satisfied: pip in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (25.2)
Collecting pip
  Downloading pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-25.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 1.6 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.9 MB/s  0:00:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2
Successfully installed pip-25.3

In [3]:
from sklearn import datasets

In [6]:
data=datasets.load_breast_cancer()

In [8]:
print(data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30)), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]), 'frame': None, 'target_names': array(['malignant', 'benign'], dtype='<U9'), 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n', 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23'), 'filename': 'breast_cancer.csv', 'data_module': 'sklearn.datasets.data'}

In [13]:
import pandas as pd
df=pd.read_csv("E:\Data analytics\__pycache__\CAR DETAILS FROM CAR DEKHO.csv")
print(df)
df.head()

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000
1                Maruti Wagon R LXI Minor  2007         135000      50000
2                    Hyundai Verna 1.6 SX  2012         600000     100000
3                  Datsun RediGO T Option  2017         250000      46000
4                   Honda Amaze VX i-DTEC  2014         450000     141000
...                                   ...   ...            ...        ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000
4337                  Maruti 800 AC BSIII  2009         110000      83000
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000
4339                     Renault KWID RXT  2016         225000      40000

        fuel seller_type transmission         owner
0     Petrol  Individual       Manual   First Owner
1     Petrol  Individual       Manual   First Owner
2     Diesel  Individual       Manual   First Owner
3     Petrol  Individual       Manual   First Owner
4     Diesel  Individual       Manual  Second Owner
...      ...         ...          ...           ...
4335  Diesel  Individual       Manual  Second Owner
4336  Diesel  Individual       Manual  Second Owner
4337  Petrol  Individual       Manual  Second Owner
4338  Diesel  Individual       Manual   First Owner
4339  Petrol  Individual       Manual   First Owner

[4340 rows x 8 columns]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [15]:
x= df.drop("selling_price",axis=1)
y=df["selling_price"]
x

,name,year,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner

In [17]:
from sklearn.model_selection import train_test_split    
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
x_train

,name,year,km_driven,fuel,seller_type,transmission,owner
227,Mahindra Scorpio S11 BSIV,2017,20000,Diesel,Individual,Manual,First Owner
964,Maruti Swift Dzire VDI,2018,50000,Diesel,Individual,Manual,First Owner
2045,Maruti Alto 800 LXI,2013,25000,Petrol,Individual,Manual,Second Owner
1025,Chevrolet Beat Diesel LS,2011,70000,Diesel,Individual,Manual,First Owner
4242,Maruti Vitara Brezza LDi Option,2017,72000,Diesel,Dealer,Manual,First Owner
...,...,...,...,...,...,...,...
3444,Toyota Innova 2.5 G (Diesel) 8 Seater BS IV,2006,50000,Diesel,Individual,Manual,First Owner
466,Tata Indica Vista Quadrajet LX,2011,80000,Diesel,Individual,Manual,First Owner
3092,Maruti Ciaz VDi Plus SHVS,2016,51000,Diesel,Dealer,Manual,First Owner
3772,Maruti Ertiga VDI,2013,80000,Diesel,Individual,Manual,First Owner
860,Hyundai Santro Xing GL Plus,2013,80000,Petrol,Individual,Manual,First Owner

In [22]:
x_train.shape

(3472, 7)

In [23]:
x_test

,name,year,km_driven,fuel,seller_type,transmission,owner
3978,Tata Manza Aqua Quadrajet BS IV,2010,80000,Diesel,Individual,Manual,First Owner
1448,Renault KWID RXT BSIV,2019,27000,Petrol,Individual,Manual,First Owner
2664,Hyundai Santro Xing GL Plus,2008,41723,Petrol,Individual,Manual,Second Owner
17,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner
1634,Mahindra TUV 300 T8 AMT,2016,60000,Diesel,Individual,Automatic,Second Owner
...,...,...,...,...,...,...,...
3468,Maruti Wagon R LXI Minor,2007,60000,Petrol,Individual,Manual,Third Owner
3164,Maruti Celerio ZDi,2015,120000,Diesel,Individual,Manual,First Owner
416,Maruti Ritz VDi,2011,40000,Diesel,Individual,Manual,Second Owner
1616,Toyota Etios Liva 1.2 VX,2017,6480,Petrol,Trustmark Dealer,Manual,First Owner
2480,Maruti Wagon R ZXI 1.2,2019,30000,Petrol,Dealer,Manual,First Owner

In [25]:
x_test.shape

(868, 7)

Applying Normalization : Minmax Scalling

In [50]:
import pandas as pd
df=pd.read_csv("E:\Data analytics\__pycache__\CAR DETAILS FROM CAR DEKHO.csv")
print(df)

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000
1                Maruti Wagon R LXI Minor  2007         135000      50000
2                    Hyundai Verna 1.6 SX  2012         600000     100000
3                  Datsun RediGO T Option  2017         250000      46000
4                   Honda Amaze VX i-DTEC  2014         450000     141000
...                                   ...   ...            ...        ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000
4337                  Maruti 800 AC BSIII  2009         110000      83000
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000
4339                     Renault KWID RXT  2016         225000      40000

        fuel seller_type transmission         owner
0     Petrol  Individual       Manual   First Owner
1     Petrol  Individual       Manual   First Owner
2     Diesel  Individual       Manual   First Owner
3     Petrol  Individual       Manual   First Owner
4     Diesel  Individual       Manual  Second Owner
...      ...         ...          ...           ...
4335  Diesel  Individual       Manual  Second Owner
4336  Diesel  Individual       Manual  Second Owner
4337  Petrol  Individual       Manual  Second Owner
4338  Diesel  Individual       Manual   First Owner
4339  Petrol  Individual       Manual   First Owner

[4340 rows x 8 columns]

In [51]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [52]:
df=df[["selling_price","km_driven","year"]]
print(df)

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

In [53]:
df

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

In [54]:
from sklearn.preprocessing  import MinMaxScaler
scaler=MinMaxScaler()
df_new=scaler.fit_transform(df)
df_new

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [55]:
df_new

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [56]:
df

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

In [57]:
s_df = pd.DataFrame(df_new, columns=df.columns)

Standardscaler

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [23]:
df= pd.read_csv("E:\Data analytics\__pycache__\Social_Network_Ads.csv")
print(df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [24]:
df.drop("User ID",axis=1,inplace=True)
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [25]:
df["Gender"] =df["Gender"].map({"Male":1, "Female":0})
df

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

traain test split

In [27]:
from sklearn.model_selection import train_test_split
x=df.drop("Purchased",axis=1)
y=df["Purchased"]

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
x_train

     Gender  Age  EstimatedSalary
3         0   27            57000
18        1   46            28000
202       0   39           134000
250       0   44            39000
274       0   57            26000
..      ...  ...              ...
71        0   24            27000
106       0   26            35000
270       0   43           133000
348       1   39            77000
102       0   32            86000

[320 rows x 3 columns]

StandardScaler

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [31]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.50447048],
       [-1.        ,  0.11069205,  0.02090805],
       [ 1.        ,  0.89565505, -1.31720709],
       [ 1.        , -1.36111358, -1.49174384],
       [-1.        , -0.18366908, -0.5899706 ],
       [-1.        , -0.57615058,  2.31897535],
       [-1.        ,  0.99377543, -1.20084925],
       [ 1.        , -0.77239133,  1.06812859],
       [ 1.        ,  2.17121993, -1.05540195],
       [ 1.        ,  0.01257167, -0.26998655],
       [ 1.        , -0.4780302 , -1.14267033],
       [ 1.        ,  0.11069205,  0.02090805],
       [ 1.        ,  1.68061805, -0.90995465],
       [-1.        ,  1.0918958 , -0.90995465],
       [-1.        ,  0.50317355,  1.21357589],
       [ 1.        , -1.06675246, -1.46265438],
       [-1.        , -1.16487283, -1.54992276],
       [-1.        , -0.0855487 ,  0.66087616],
       [ 1.        ,  0.40505317, -0.47361276],
       [ 1.        , -0.28178945, -0.26998655],
       [ 1.        , -0.87051171,  0.13726589],
       [-1.        ,  0.01257167,  0.28271318],
       [ 1.        ,  0.6994143 , -1.28811763],
       [-1.        ,  1.58249768,  1.09721805],
       [ 1.        ,  0.79753468, -1.37538601],
       [-1.        , -1.45923396, -1.22993871],
       [ 1.        , -0.0855487 ,  0.13726589],
       [ 1.        ,  0.40505317, -0.15362871],
       [-1.        , -0.28178945,  0.02090805],
       [-1.        ,  1.28813655,  2.20261751],
       [ 1.        ,  0.11069205,  0.74814454],
       [-1.        , -1.36111358,  0.54451832],
       [-1.        ,  1.97497918,  0.71905508],
       [ 1.        , -1.26299321, -1.40447546],
       [ 1.        ,  0.3069328 , -0.32816546],
       [ 1.        , -0.96863208,  0.54451832],
       [-1.        ,  0.40505317,  0.28271318],
       [-1.        ,  0.40505317,  1.09721805],
       [-1.        ,  0.79753468,  0.74814454],
       [-1.        ,  0.89565505,  1.24266535],
       [-1.        , -0.4780302 , -1.22993871],
       [ 1.        , -1.85171546, -1.31720709],
       [ 1.        ,  1.0918958 ,  0.54451832],
       [-1.        , -0.67427095, -1.60810168],
       [-1.        , -0.77239133,  0.25362372],
       [ 1.        ,  0.99377543,  2.05717021],
       [-1.        , -0.57615058,  1.35902318],
       [-1.        , -0.0855487 ,  0.02090805],
       [-1.        , -1.94983583,  0.45724994],
       [-1.        ,  0.40505317,  0.25362372],
       [-1.        , -1.06675246,  0.39907102],
       [ 1.        ,  0.20881242, -0.15362871],
       [ 1.        ,  1.87685881,  0.10817643],
       [-1.        , -1.16487283, -1.60810168],
       [-1.        , -1.16487283,  0.28271318],
       [ 1.        , -0.87051171, -0.79359682],
       [-1.        , -0.4780302 ,  2.28988589],
       [ 1.        ,  0.11069205, -0.82268628],
       [-1.        ,  1.58249768,  0.98086021],
       [ 1.        , -0.18366908, -1.08449141],
       [-1.        ,  0.79753468, -1.11358087],
       [-1.        ,  0.20881242,  2.08625967],
       [-1.        , -0.0855487 , -0.24089709],
       [ 1.        , -0.87051171,  2.26079643],
       [-1.        , -0.0855487 , -0.38634438],
       [ 1.        , -0.28178945, -0.5899706 ],
       [-1.        ,  0.40505317, -0.50270222],
       [ 1.        , -0.28178945, -0.93904411],
       [-1.        ,  0.3069328 , -1.17175979],
       [-1.        ,  0.20881242,  0.04999751],
       [ 1.        , -1.16487283, -1.60810168],
       [-1.        , -0.67427095, -0.06636033],
       [ 1.        , -0.28178945, -0.50270222],
       [-1.        , -0.28178945, -1.31720709],
       [ 1.        , -0.77239133,  0.54451832],
       [ 1.        ,  0.3069328 ,  0.04999751],
       [ 1.        , -0.96863208,  1.53355994],
       [-1.        ,  0.79753468,  0.3408921 ],
       [-1.        , -1.55735433, -0.21180763],
       [-1.        ,  0.6994143 , -1.40447546],
       [ 1.        , -0.77239133, -0.61906006],
       [-1.        , -0.37990983, -1.31720709],
       [-1.        ,  0.20881242,  0.13726589],
       [-1.        , -0.57615058,  1.35902318],
       [-1.        , -1.45923396,  0.3408921 ],
       [ 1.        , -1.16487283,  0.28271318],
       [-1.        ,  0.99377543,  1.76627562],
       [ 1.        ,  2.07309956,  2.11534913],
       [ 1.        , -0.28178945, -0.4445233 ],
       [ 1.        , -0.37990983, -0.79359682],
       [-1.        ,  0.11069205, -0.26998655],
       [-1.        , -1.06675246,  0.74814454],
       [ 1.        ,  2.17121993,  0.36998156],
       [ 1.        , -1.36111358, -0.4445233 ],
       [ 1.        ,  1.97497918,  2.14443859],
       [-1.        ,  1.4843773 ,  0.98086021],
       [ 1.        , -0.28178945,  0.25362372],
       [ 1.        , -0.18366908,  0.83541291],
       [ 1.        ,  1.87685881, -0.29907601],
       [-1.        , -0.0855487 ,  1.94081237],
       [ 1.        , -0.4780302 , -0.79359682],
       [-1.        ,  0.3069328 ,  0.02090805],
       [-1.        ,  1.38625693, -1.43356492],
       [ 1.        ,  1.38625693,  2.31897535],
       [ 1.        , -0.0855487 , -0.00818141],
       [-1.        , -1.16487283,  0.39907102],
       [-1.        , -1.16487283,  0.04999751],
       [-1.        , -1.16487283, -0.53179168],
       [-1.        ,  0.3069328 , -0.29907601],
       [ 1.        , -0.67427095, -0.12453925],
       [ 1.        , -0.0855487 ,  2.14443859],
       [ 1.        ,  0.01257167, -0.26998655],
       [-1.        , -0.67427095, -1.05540195],
       [-1.        ,  0.40505317,  0.13726589],
       [ 1.        ,  0.79753468,  1.35902318],
       [ 1.        , -0.18366908, -0.53179168],
       [ 1.        ,  0.01257167,  0.02090805],
       [ 1.        ,  1.0918958 ,  0.51542886],
       [-1.        ,  1.87685881, -1.08449141],
       [-1.        ,  0.99377543,  1.96990183],
       [-1.        ,  0.89565505, -0.5899706 ],
       [-1.        , -0.4780302 , -0.03727087],
       [-1.        , -0.0855487 ,  2.20261751],
       [-1.        , -1.75359508,  0.3408921 ],
       [ 1.        ,  0.20881242, -0.67723898],
       [ 1.        , -0.28178945, -1.40447546],
       [-1.        , -1.75359508, -0.99722303],
       [-1.        ,  0.6994143 , -0.7354179 ],
       [-1.        , -1.16487283, -0.79359682],
       [-1.        ,  1.97497918,  0.89359183],
       [ 1.        ,  0.20881242, -0.38634438],
       [-1.        ,  0.01257167,  1.21357589],
       [-1.        , -0.0855487 ,  0.28271318],
       [ 1.        ,  1.0918958 , -1.22993871],
       [-1.        , -0.18366908,  0.13726589],
       [-1.        ,  0.3069328 ,  0.04999751],
       [-1.        , -0.28178945, -0.29907601],
       [ 1.        ,  0.50317355,  1.7080967 ],
       [ 1.        ,  0.3069328 ,  0.4863394 ],
       [-1.        ,  0.01257167,  1.24266535],
       [-1.        ,  1.97497918, -1.37538601],
       [ 1.        , -1.16487283, -1.11358087],
       [ 1.        , -0.57615058, -1.5208333 ],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        , -0.67427095, -1.5208333 ],
       [ 1.        , -0.28178945,  0.51542886],
       [-1.        ,  0.99377543, -1.02631249],
       [ 1.        , -1.06675246,  0.54451832],
       [-1.        , -0.28178945,  0.777234  ],
       [ 1.        ,  0.40505317,  0.07908697],
       [-1.        , -1.65547471, -0.06636033],
       [-1.        ,  0.3069328 ,  0.04999751],
       [-1.        , -0.4780302 , -0.29907601],
       [ 1.        ,  0.11069205,  1.853544  ],
       [-1.        , -0.96863208,  0.39907102],
       [ 1.        ,  0.79753468,  0.51542886],
       [ 1.        , -1.36111358, -0.35725492],
       [-1.        , -0.67427095,  1.38811264],
       [-1.        ,  1.19001618,  0.51542886],
       [-1.        , -1.75359508,  0.3408921 ],
       [-1.        , -0.57615058,  1.88263345],
       [ 1.        , -1.75359508,  0.45724994],
       [ 1.        , -0.28178945, -1.25902817],
       [ 1.        , -0.87051171, -0.79359682],
       [ 1.        , -1.65547471,  0.51542886],
       [ 1.        , -0.28178945, -0.32816546],
       [ 1.        ,  0.6994143 , -1.11358087],
       [ 1.        ,  2.17121993, -0.82268628],
       [ 1.        , -0.28178945,  0.60269724],
       [-1.        , -0.28178945, -0.76450736],
       [-1.        , -1.94983583, -0.76450736],
       [ 1.        ,  0.40505317,  2.28988589],
       [ 1.        ,  0.6994143 ,  0.25362372],
       [-1.        ,  0.20881242, -0.29907601],
       [ 1.        , -1.36111358, -1.37538601],
       [-1.        , -0.4780302 , -0.56088114],
       [-1.        ,  0.40505317, -0.00818141],
       [-1.        ,  1.68061805,  1.73718616],
       [-1.        ,  1.19001618, -0.76450736],
       [-1.        ,  0.99377543,  1.4172021 ],
       [ 1.        , -1.85171546,  0.16635535],
       [-1.        ,  0.3069328 ,  0.04999751],
       [ 1.        ,  0.20881242,  0.02090805],
       [ 1.        , -1.06675246,  0.51542886],
       [-1.        , -0.18366908,  1.62082832],
       [ 1.        , -0.28178945,  0.13726589],
       [ 1.        , -0.28178945, -0.35725492],
       [ 1.        , -0.37990983,  1.30084427],
       [ 1.        , -0.28178945,  0.07908697],
       [-1.        ,  2.17121993,  1.09721805],
       [ 1.        , -1.26299321,  0.4863394 ],
       [-1.        , -1.06675246, -0.47361276],
       [-1.        , -1.65547471, -1.57901222],
       [ 1.        , -0.0855487 ,  0.10817643],
       [ 1.        , -0.28178945, -0.90995465],
       [ 1.        ,  1.58249768, -0.00818141],
       [-1.        ,  0.89565505, -1.17175979],
       [-1.        ,  0.01257167, -0.5899706 ],
       [-1.        , -0.28178945,  2.23170697],
       [-1.        , -0.28178945,  0.19544481],
       [ 1.        ,  0.3069328 ,  0.25362372],
       [-1.        , -0.0855487 , -1.08449141],
       [-1.        ,  2.17121993, -0.70632844],
       [-1.        , -0.96863208, -0.32816546],
       [-1.        , -1.45923396, -0.12453925],
       [ 1.        , -1.45923396, -0.21180763],
       [ 1.        , -0.77239133, -1.54992276],
       [ 1.        , -1.26299321, -1.08449141],
       [-1.        ,  2.07309956,  0.36998156],
       [-1.        ,  1.97497918, -0.93904411],
       [ 1.        , -1.94983583,  0.3408921 ],
       [ 1.        ,  0.79753468, -0.32816546],
       [-1.        , -1.06675246, -1.54992276],
       [-1.        ,  1.97497918, -0.67723898],
       [-1.        ,  0.99377543, -1.17175979],
       [ 1.        ,  1.0918958 , -0.15362871],
       [-1.        ,  1.19001618, -0.99722303],
       [ 1.        ,  1.4843773 ,  0.04999751],
       [ 1.        ,  0.20881242, -0.38634438],
       [-1.        ,  1.38625693,  1.27175481],
       [-1.        ,  2.07309956, -0.82268628],
       [-1.        , -0.18366908, -0.21180763],
       [ 1.        ,  0.40505317,  0.98086021],
       [ 1.        , -0.0855487 , -0.53179168],
       [ 1.        ,  0.99377543, -1.08449141],
       [-1.        ,  2.07309956, -1.20084925],
       [ 1.        , -0.0855487 ,  0.25362372],
       [ 1.        ,  0.20881242, -0.26998655],
       [ 1.        ,  1.0918958 ,  0.10817643],
       [ 1.        , -1.26299321,  0.57360778],
       [ 1.        , -0.77239133, -1.60810168],
       [ 1.        ,  0.20881242,  0.22453427],
       [ 1.        , -1.36111358,  0.39907102],
       [-1.        ,  0.01257167, -0.5899706 ],
       [-1.        ,  0.6994143 ,  1.76627562],
       [ 1.        , -1.65547471,  0.04999751],
       [-1.        , -0.28178945, -1.37538601],
       [ 1.        , -0.28178945, -1.46265438],
       [-1.        , -0.67427095,  0.54451832],
       [ 1.        , -0.77239133,  0.28271318],
       [-1.        ,  0.89565505, -0.67723898],
       [ 1.        , -1.06675246,  0.57360778],
       [-1.        , -0.28178945,  0.04999751],
       [-1.        , -0.77239133,  1.32993372],
       [ 1.        ,  0.11069205,  1.50447048],
       [-1.        , -0.87051171,  0.36998156],
       [-1.        ,  0.3069328 , -0.21180763],
       [ 1.        ,  0.99377543,  0.57360778],
       [ 1.        ,  0.01257167, -0.32816546],
       [ 1.        , -0.57615058, -1.5208333 ],
       [-1.        ,  0.11069205,  0.13726589],
       [ 1.        , -1.16487283,  0.31180264],
       [ 1.        ,  0.11069205,  1.03903913],
       [-1.        , -1.55735433, -0.4445233 ],
       [ 1.        , -0.18366908,  1.38811264],
       [ 1.        ,  2.17121993, -0.82268628],
       [-1.        , -0.96863208, -0.4445233 ],
       [-1.        ,  1.28813655,  1.853544  ],
       [ 1.        ,  1.0918958 , -1.22993871],
       [ 1.        , -0.18366908, -0.29907601],
       [-1.        ,  1.77873843,  0.98086021],
       [-1.        , -1.06675246, -0.35725492],
       [-1.        , -1.36111358, -1.11358087],
       [-1.        , -0.37990983,  0.04999751],
       [ 1.        , -0.96863208, -1.11358087],
       [-1.        ,  1.19001618, -1.46265438],
       [-1.        , -0.4780302 , -0.85177573],
       [-1.        , -0.87051171, -0.67723898],
       [ 1.        , -1.55735433, -1.5208333 ],
       [ 1.        , -0.77239133,  1.88263345],
       [ 1.        ,  0.89565505,  1.00994967],
       [ 1.        ,  0.79753468,  0.25362372],
       [-1.        ,  0.99377543,  1.853544  ],
       [-1.        ,  0.89565505, -0.61906006],
       [-1.        ,  1.0918958 ,  2.05717021],
       [ 1.        , -0.57615058,  0.86450237],
       [ 1.        ,  0.01257167,  0.02090805],
       [-1.        , -1.85171546, -1.28811763],
       [ 1.        , -0.0855487 ,  0.19544481],
       [-1.        ,  0.89565505, -0.56088114],
       [ 1.        ,  0.20881242, -0.38634438],
       [ 1.        , -0.18366908,  1.59173886],
       [ 1.        , -1.75359508,  0.10817643],
       [ 1.        , -0.67427095, -0.35725492],
       [ 1.        ,  0.3069328 , -0.7354179 ],
       [ 1.        ,  0.40505317, -0.47361276],
       [-1.        , -0.96863208, -0.96813357],
       [-1.        ,  0.11069205,  0.07908697],
       [-1.        , -0.96863208,  0.42816048],
       [ 1.        ,  0.01257167, -0.56088114],
       [ 1.        ,  0.89565505, -0.79359682],
       [ 1.        , -0.0855487 ,  0.04999751],
       [-1.        ,  1.0918958 , -0.99722303],
       [ 1.        ,  0.6994143 , -1.40447546],
       [ 1.        , -0.28178945,  0.04999751],
       [-1.        , -1.36111358, -1.25902817],
       [-1.        , -1.16487283, -1.02631249],
       [-1.        ,  0.50317355,  1.82445454],
       [ 1.        ,  0.11069205,  0.19544481],
       [-1.        , -0.57615058,  0.45724994]])

In [32]:
x_test

array([[-1.        ,  0.79753468, -1.40447546],
       [-1.        ,  2.07309956,  0.51542886],
       [-1.        , -0.96863208, -0.76450736],
       [-1.        ,  0.99377543,  0.74814454],
       [-1.        , -0.87051171, -1.22993871],
       [-1.        , -0.77239133, -0.24089709],
       [-1.        ,  0.89565505,  1.06812859],
       [-1.        , -0.87051171,  0.36998156],
       [ 1.        ,  0.20881242,  0.13726589],
       [ 1.        ,  0.40505317, -0.15362871],
       [-1.        , -0.28178945, -0.15362871],
       [-1.        ,  1.4843773 , -1.05540195],
       [-1.        , -1.45923396, -0.64814952],
       [-1.        , -1.75359508, -1.37538601],
       [ 1.        , -0.77239133,  0.4863394 ],
       [ 1.        , -0.28178945,  1.09721805],
       [-1.        ,  1.38625693, -0.93904411],
       [-1.        ,  0.79753468,  0.10817643],
       [ 1.        ,  0.11069205, -0.82268628],
       [ 1.        ,  1.77873843, -0.29907601],
       [-1.        , -1.55735433, -1.25902817],
       [ 1.        , -0.87051171,  0.28271318],
       [ 1.        ,  0.89565505, -1.37538601],
       [-1.        ,  2.07309956,  0.16635535],
       [ 1.        , -1.85171546, -1.49174384],
       [ 1.        ,  1.28813655, -1.37538601],
       [ 1.        ,  0.40505317,  0.28271318],
       [ 1.        , -0.0855487 , -0.50270222],
       [-1.        ,  1.68061805,  1.59173886],
       [-1.        , -1.85171546, -1.43356492],
       [-1.        ,  0.79753468, -0.85177573],
       [ 1.        , -1.85171546, -0.00818141],
       [ 1.        , -0.18366908,  2.14443859],
       [ 1.        , -0.96863208,  0.25362372],
       [ 1.        ,  0.20881242,  1.06812859],
       [ 1.        , -0.28178945,  0.13726589],
       [ 1.        , -0.0855487 , -0.4445233 ],
       [-1.        ,  0.01257167, -0.15362871],
       [ 1.        , -1.16487283, -1.17175979],
       [-1.        , -1.94983583, -0.06636033],
       [ 1.        ,  0.99377543, -1.08449141],
       [-1.        , -1.36111358, -0.4445233 ],
       [ 1.        , -1.94983583, -0.53179168],
       [ 1.        ,  0.89565505, -1.46265438],
       [ 1.        , -1.75359508, -0.61906006],
       [-1.        ,  0.60129393,  1.99899129],
       [ 1.        , -0.87051171, -0.26998655],
       [-1.        , -0.67427095,  0.02090805],
       [ 1.        ,  0.99377543, -0.85177573],
       [-1.        , -0.37990983, -0.79359682],
       [ 1.        , -1.26299321,  0.25362372],
       [-1.        ,  1.4843773 ,  0.3408921 ],
       [-1.        ,  0.01257167, -0.4445233 ],
       [ 1.        , -1.26299321,  0.28271318],
       [-1.        , -0.0855487 ,  0.28271318],
       [-1.        , -1.06675246, -1.14267033],
       [ 1.        ,  2.17121993,  0.92268129],
       [-1.        , -1.16487283,  1.38811264],
       [ 1.        , -0.67427095,  0.10817643],
       [ 1.        , -0.67427095,  0.16635535],
       [-1.        ,  0.3069328 , -0.56088114],
       [-1.        , -0.28178945, -0.38634438],
       [-1.        ,  1.38625693,  0.57360778],
       [-1.        , -0.96863208,  0.4863394 ],
       [ 1.        , -0.96863208, -0.32816546],
       [-1.        , -1.06675246,  1.94081237],
       [-1.        ,  0.40505317,  0.57360778],
       [-1.        ,  0.89565505,  2.14443859],
       [-1.        ,  0.11069205, -0.32816546],
       [-1.        , -0.4780302 ,  1.24266535],
       [-1.        ,  1.38625693,  1.96990183],
       [ 1.        , -1.85171546,  0.42816048],
       [ 1.        , -1.06675246, -0.35725492],
       [ 1.        , -1.45923396, -1.46265438],
       [ 1.        ,  0.89565505, -1.05540195],
       [-1.        , -0.28178945, -0.5899706 ],
       [ 1.        ,  1.77873843,  1.82445454],
       [-1.        ,  1.58249768, -1.28811763],
       [-1.        , -0.28178945, -0.67723898],
       [-1.        , -0.0855487 ,  0.22453427]])

In [33]:
x_train

array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.50447048],
       [-1.        ,  0.11069205,  0.02090805],
       [ 1.        ,  0.89565505, -1.31720709],
       [ 1.        , -1.36111358, -1.49174384],
       [-1.        , -0.18366908, -0.5899706 ],
       [-1.        , -0.57615058,  2.31897535],
       [-1.        ,  0.99377543, -1.20084925],
       [ 1.        , -0.77239133,  1.06812859],
       [ 1.        ,  2.17121993, -1.05540195],
       [ 1.        ,  0.01257167, -0.26998655],
       [ 1.        , -0.4780302 , -1.14267033],
       [ 1.        ,  0.11069205,  0.02090805],
       [ 1.        ,  1.68061805, -0.90995465],
       [-1.        ,  1.0918958 , -0.90995465],
       [-1.        ,  0.50317355,  1.21357589],
       [ 1.        , -1.06675246, -1.46265438],
       [-1.        , -1.16487283, -1.54992276],
       [-1.        , -0.0855487 ,  0.66087616],
       [ 1.        ,  0.40505317, -0.47361276],
       [ 1.        , -0.28178945, -0.26998655],
       [ 1.        , -0.87051171,  0.13726589],
       [-1.        ,  0.01257167,  0.28271318],
       [ 1.        ,  0.6994143 , -1.28811763],
       [-1.        ,  1.58249768,  1.09721805],
       [ 1.        ,  0.79753468, -1.37538601],
       [-1.        , -1.45923396, -1.22993871],
       [ 1.        , -0.0855487 ,  0.13726589],
       [ 1.        ,  0.40505317, -0.15362871],
       [-1.        , -0.28178945,  0.02090805],
       [-1.        ,  1.28813655,  2.20261751],
       [ 1.        ,  0.11069205,  0.74814454],
       [-1.        , -1.36111358,  0.54451832],
       [-1.        ,  1.97497918,  0.71905508],
       [ 1.        , -1.26299321, -1.40447546],
       [ 1.        ,  0.3069328 , -0.32816546],
       [ 1.        , -0.96863208,  0.54451832],
       [-1.        ,  0.40505317,  0.28271318],
       [-1.        ,  0.40505317,  1.09721805],
       [-1.        ,  0.79753468,  0.74814454],
       [-1.        ,  0.89565505,  1.24266535],
       [-1.        , -0.4780302 , -1.22993871],
       [ 1.        , -1.85171546, -1.31720709],
       [ 1.        ,  1.0918958 ,  0.54451832],
       [-1.        , -0.67427095, -1.60810168],
       [-1.        , -0.77239133,  0.25362372],
       [ 1.        ,  0.99377543,  2.05717021],
       [-1.        , -0.57615058,  1.35902318],
       [-1.        , -0.0855487 ,  0.02090805],
       [-1.        , -1.94983583,  0.45724994],
       [-1.        ,  0.40505317,  0.25362372],
       [-1.        , -1.06675246,  0.39907102],
       [ 1.        ,  0.20881242, -0.15362871],
       [ 1.        ,  1.87685881,  0.10817643],
       [-1.        , -1.16487283, -1.60810168],
       [-1.        , -1.16487283,  0.28271318],
       [ 1.        , -0.87051171, -0.79359682],
       [-1.        , -0.4780302 ,  2.28988589],
       [ 1.        ,  0.11069205, -0.82268628],
       [-1.        ,  1.58249768,  0.98086021],
       [ 1.        , -0.18366908, -1.08449141],
       [-1.        ,  0.79753468, -1.11358087],
       [-1.        ,  0.20881242,  2.08625967],
       [-1.        , -0.0855487 , -0.24089709],
       [ 1.        , -0.87051171,  2.26079643],
       [-1.        , -0.0855487 , -0.38634438],
       [ 1.        , -0.28178945, -0.5899706 ],
       [-1.        ,  0.40505317, -0.50270222],
       [ 1.        , -0.28178945, -0.93904411],
       [-1.        ,  0.3069328 , -1.17175979],
       [-1.        ,  0.20881242,  0.04999751],
       [ 1.        , -1.16487283, -1.60810168],
       [-1.        , -0.67427095, -0.06636033],
       [ 1.        , -0.28178945, -0.50270222],
       [-1.        , -0.28178945, -1.31720709],
       [ 1.        , -0.77239133,  0.54451832],
       [ 1.        ,  0.3069328 ,  0.04999751],
       [ 1.        , -0.96863208,  1.53355994],
       [-1.        ,  0.79753468,  0.3408921 ],
       [-1.        , -1.55735433, -0.21180763],
       [-1.        ,  0.6994143 , -1.40447546],
       [ 1.        , -0.77239133, -0.61906006],
       [-1.        , -0.37990983, -1.31720709],
       [-1.        ,  0.20881242,  0.13726589],
       [-1.        , -0.57615058,  1.35902318],
       [-1.        , -1.45923396,  0.3408921 ],
       [ 1.        , -1.16487283,  0.28271318],
       [-1.        ,  0.99377543,  1.76627562],
       [ 1.        ,  2.07309956,  2.11534913],
       [ 1.        , -0.28178945, -0.4445233 ],
       [ 1.        , -0.37990983, -0.79359682],
       [-1.        ,  0.11069205, -0.26998655],
       [-1.        , -1.06675246,  0.74814454],
       [ 1.        ,  2.17121993,  0.36998156],
       [ 1.        , -1.36111358, -0.4445233 ],
       [ 1.        ,  1.97497918,  2.14443859],
       [-1.        ,  1.4843773 ,  0.98086021],
       [ 1.        , -0.28178945,  0.25362372],
       [ 1.        , -0.18366908,  0.83541291],
       [ 1.        ,  1.87685881, -0.29907601],
       [-1.        , -0.0855487 ,  1.94081237],
       [ 1.        , -0.4780302 , -0.79359682],
       [-1.        ,  0.3069328 ,  0.02090805],
       [-1.        ,  1.38625693, -1.43356492],
       [ 1.        ,  1.38625693,  2.31897535],
       [ 1.        , -0.0855487 , -0.00818141],
       [-1.        , -1.16487283,  0.39907102],
       [-1.        , -1.16487283,  0.04999751],
       [-1.        , -1.16487283, -0.53179168],
       [-1.        ,  0.3069328 , -0.29907601],
       [ 1.        , -0.67427095, -0.12453925],
       [ 1.        , -0.0855487 ,  2.14443859],
       [ 1.        ,  0.01257167, -0.26998655],
       [-1.        , -0.67427095, -1.05540195],
       [-1.        ,  0.40505317,  0.13726589],
       [ 1.        ,  0.79753468,  1.35902318],
       [ 1.        , -0.18366908, -0.53179168],
       [ 1.        ,  0.01257167,  0.02090805],
       [ 1.        ,  1.0918958 ,  0.51542886],
       [-1.        ,  1.87685881, -1.08449141],
       [-1.        ,  0.99377543,  1.96990183],
       [-1.        ,  0.89565505, -0.5899706 ],
       [-1.        , -0.4780302 , -0.03727087],
       [-1.        , -0.0855487 ,  2.20261751],
       [-1.        , -1.75359508,  0.3408921 ],
       [ 1.        ,  0.20881242, -0.67723898],
       [ 1.        , -0.28178945, -1.40447546],
       [-1.        , -1.75359508, -0.99722303],
       [-1.        ,  0.6994143 , -0.7354179 ],
       [-1.        , -1.16487283, -0.79359682],
       [-1.        ,  1.97497918,  0.89359183],
       [ 1.        ,  0.20881242, -0.38634438],
       [-1.        ,  0.01257167,  1.21357589],
       [-1.        , -0.0855487 ,  0.28271318],
       [ 1.        ,  1.0918958 , -1.22993871],
       [-1.        , -0.18366908,  0.13726589],
       [-1.        ,  0.3069328 ,  0.04999751],
       [-1.        , -0.28178945, -0.29907601],
       [ 1.        ,  0.50317355,  1.7080967 ],
       [ 1.        ,  0.3069328 ,  0.4863394 ],
       [-1.        ,  0.01257167,  1.24266535],
       [-1.        ,  1.97497918, -1.37538601],
       [ 1.        , -1.16487283, -1.11358087],
       [ 1.        , -0.57615058, -1.5208333 ],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        , -0.67427095, -1.5208333 ],
       [ 1.        , -0.28178945,  0.51542886],
       [-1.        ,  0.99377543, -1.02631249],
       [ 1.        , -1.06675246,  0.54451832],
       [-1.        , -0.28178945,  0.777234  ],
       [ 1.        ,  0.40505317,  0.07908697],
       [-1.        , -1.65547471, -0.06636033],
       [-1.        ,  0.3069328 ,  0.04999751],
       [-1.        , -0.4780302 , -0.29907601],
       [ 1.        ,  0.11069205,  1.853544  ],
       [-1.        , -0.96863208,  0.39907102],
       [ 1.        ,  0.79753468,  0.51542886],
       [ 1.        , -1.36111358, -0.35725492],
       [-1.        , -0.67427095,  1.38811264],
       [-1.        ,  1.19001618,  0.51542886],
       [-1.        , -1.75359508,  0.3408921 ],
       [-1.        , -0.57615058,  1.88263345],
       [ 1.        , -1.75359508,  0.45724994],
       [ 1.        , -0.28178945, -1.25902817],
       [ 1.        , -0.87051171, -0.79359682],
       [ 1.        , -1.65547471,  0.51542886],
       [ 1.        , -0.28178945, -0.32816546],
       [ 1.        ,  0.6994143 , -1.11358087],
       [ 1.        ,  2.17121993, -0.82268628],
       [ 1.        , -0.28178945,  0.60269724],
       [-1.        , -0.28178945, -0.76450736],
       [-1.        , -1.94983583, -0.76450736],
       [ 1.        ,  0.40505317,  2.28988589],
       [ 1.        ,  0.6994143 ,  0.25362372],
       [-1.        ,  0.20881242, -0.29907601],
       [ 1.        , -1.36111358, -1.37538601],
       [-1.        , -0.4780302 , -0.56088114],
       [-1.        ,  0.40505317, -0.00818141],
       [-1.        ,  1.68061805,  1.73718616],
       [-1.        ,  1.19001618, -0.76450736],
       [-1.        ,  0.99377543,  1.4172021 ],
       [ 1.        , -1.85171546,  0.16635535],
       [-1.        ,  0.3069328 ,  0.04999751],
       [ 1.        ,  0.20881242,  0.02090805],
       [ 1.        , -1.06675246,  0.51542886],
       [-1.        , -0.18366908,  1.62082832],
       [ 1.        , -0.28178945,  0.13726589],
       [ 1.        , -0.28178945, -0.35725492],
       [ 1.        , -0.37990983,  1.30084427],
       [ 1.        , -0.28178945,  0.07908697],
       [-1.        ,  2.17121993,  1.09721805],
       [ 1.        , -1.26299321,  0.4863394 ],
       [-1.        , -1.06675246, -0.47361276],
       [-1.        , -1.65547471, -1.57901222],
       [ 1.        , -0.0855487 ,  0.10817643],
       [ 1.        , -0.28178945, -0.90995465],
       [ 1.        ,  1.58249768, -0.00818141],
       [-1.        ,  0.89565505, -1.17175979],
       [-1.        ,  0.01257167, -0.5899706 ],
       [-1.        , -0.28178945,  2.23170697],
       [-1.        , -0.28178945,  0.19544481],
       [ 1.        ,  0.3069328 ,  0.25362372],
       [-1.        , -0.0855487 , -1.08449141],
       [-1.        ,  2.17121993, -0.70632844],
       [-1.        , -0.96863208, -0.32816546],
       [-1.        , -1.45923396, -0.12453925],
       [ 1.        , -1.45923396, -0.21180763],
       [ 1.        , -0.77239133, -1.54992276],
       [ 1.        , -1.26299321, -1.08449141],
       [-1.        ,  2.07309956,  0.36998156],
       [-1.        ,  1.97497918, -0.93904411],
       [ 1.        , -1.94983583,  0.3408921 ],
       [ 1.        ,  0.79753468, -0.32816546],
       [-1.        , -1.06675246, -1.54992276],
       [-1.        ,  1.97497918, -0.67723898],
       [-1.        ,  0.99377543, -1.17175979],
       [ 1.        ,  1.0918958 , -0.15362871],
       [-1.        ,  1.19001618, -0.99722303],
       [ 1.        ,  1.4843773 ,  0.04999751],
       [ 1.        ,  0.20881242, -0.38634438],
       [-1.        ,  1.38625693,  1.27175481],
       [-1.        ,  2.07309956, -0.82268628],
       [-1.        , -0.18366908, -0.21180763],
       [ 1.        ,  0.40505317,  0.98086021],
       [ 1.        , -0.0855487 , -0.53179168],
       [ 1.        ,  0.99377543, -1.08449141],
       [-1.        ,  2.07309956, -1.20084925],
       [ 1.        , -0.0855487 ,  0.25362372],
       [ 1.        ,  0.20881242, -0.26998655],
       [ 1.        ,  1.0918958 ,  0.10817643],
       [ 1.        , -1.26299321,  0.57360778],
       [ 1.        , -0.77239133, -1.60810168],
       [ 1.        ,  0.20881242,  0.22453427],
       [ 1.        , -1.36111358,  0.39907102],
       [-1.        ,  0.01257167, -0.5899706 ],
       [-1.        ,  0.6994143 ,  1.76627562],
       [ 1.        , -1.65547471,  0.04999751],
       [-1.        , -0.28178945, -1.37538601],
       [ 1.        , -0.28178945, -1.46265438],
       [-1.        , -0.67427095,  0.54451832],
       [ 1.        , -0.77239133,  0.28271318],
       [-1.        ,  0.89565505, -0.67723898],
       [ 1.        , -1.06675246,  0.57360778],
       [-1.        , -0.28178945,  0.04999751],
       [-1.        , -0.77239133,  1.32993372],
       [ 1.        ,  0.11069205,  1.50447048],
       [-1.        , -0.87051171,  0.36998156],
       [-1.        ,  0.3069328 , -0.21180763],
       [ 1.        ,  0.99377543,  0.57360778],
       [ 1.        ,  0.01257167, -0.32816546],
       [ 1.        , -0.57615058, -1.5208333 ],
       [-1.        ,  0.11069205,  0.13726589],
       [ 1.        , -1.16487283,  0.31180264],
       [ 1.        ,  0.11069205,  1.03903913],
       [-1.        , -1.55735433, -0.4445233 ],
       [ 1.        , -0.18366908,  1.38811264],
       [ 1.        ,  2.17121993, -0.82268628],
       [-1.        , -0.96863208, -0.4445233 ],
       [-1.        ,  1.28813655,  1.853544  ],
       [ 1.        ,  1.0918958 , -1.22993871],
       [ 1.        , -0.18366908, -0.29907601],
       [-1.        ,  1.77873843,  0.98086021],
       [-1.        , -1.06675246, -0.35725492],
       [-1.        , -1.36111358, -1.11358087],
       [-1.        , -0.37990983,  0.04999751],
       [ 1.        , -0.96863208, -1.11358087],
       [-1.        ,  1.19001618, -1.46265438],
       [-1.        , -0.4780302 , -0.85177573],
       [-1.        , -0.87051171, -0.67723898],
       [ 1.        , -1.55735433, -1.5208333 ],
       [ 1.        , -0.77239133,  1.88263345],
       [ 1.        ,  0.89565505,  1.00994967],
       [ 1.        ,  0.79753468,  0.25362372],
       [-1.        ,  0.99377543,  1.853544  ],
       [-1.        ,  0.89565505, -0.61906006],
       [-1.        ,  1.0918958 ,  2.05717021],
       [ 1.        , -0.57615058,  0.86450237],
       [ 1.        ,  0.01257167,  0.02090805],
       [-1.        , -1.85171546, -1.28811763],
       [ 1.        , -0.0855487 ,  0.19544481],
       [-1.        ,  0.89565505, -0.56088114],
       [ 1.        ,  0.20881242, -0.38634438],
       [ 1.        , -0.18366908,  1.59173886],
       [ 1.        , -1.75359508,  0.10817643],
       [ 1.        , -0.67427095, -0.35725492],
       [ 1.        ,  0.3069328 , -0.7354179 ],
       [ 1.        ,  0.40505317, -0.47361276],
       [-1.        , -0.96863208, -0.96813357],
       [-1.        ,  0.11069205,  0.07908697],
       [-1.        , -0.96863208,  0.42816048],
       [ 1.        ,  0.01257167, -0.56088114],
       [ 1.        ,  0.89565505, -0.79359682],
       [ 1.        , -0.0855487 ,  0.04999751],
       [-1.        ,  1.0918958 , -0.99722303],
       [ 1.        ,  0.6994143 , -1.40447546],
       [ 1.        , -0.28178945,  0.04999751],
       [-1.        , -1.36111358, -1.25902817],
       [-1.        , -1.16487283, -1.02631249],
       [-1.        ,  0.50317355,  1.82445454],
       [ 1.        ,  0.11069205,  0.19544481],
       [-1.        , -0.57615058,  0.45724994]])

In [34]:
x_train_scaled=pd.DataFrame(data=x_train,columns=x_train.columns)
x_test_scaled=pd.DataFrame(data=x_test,columns=x_test.columns)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

AttributeError: 'numpy.ndarray' object has no attribute 'describe'